theme = "bad-wolf"
icons = "awesome5"

[[block]]
block = "keyboard_layout"

[[block]]
block = "memory"

[[block]]
block = "battery"
driver = "upower"
format = "{percentage} {time}"

[[block]]
block = "music"
player = "spotify"
dynamic_width = true
buttons = ["prev", "play", "next"]
on_collapsed_click = "spotify"

[[block]]
block = "sound"

[[block]]
block = "net"
device = "wlp6s0"
format = "{ssid} {signal_strength} {speed_up;M} {speed_down;M}"

[[block]]
block = "time"
format = "%a %d/%m/%Y %T"
interval = 1
locale = "en_GB"

